/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ProductsRouteImport } from './routes/products'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CategoriesRouteImport } from './routes/categories'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsedProductProductIdRouteImport } from './routes/used-product.$productId'
import { Route as SellerSellerIdRouteImport } from './routes/seller.$sellerId'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as MarketplaceProductIdRouteImport } from './routes/marketplace.$productId'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesRoute = CategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsedProductProductIdRoute = UsedProductProductIdRouteImport.update({
  id: '/used-product/$productId',
  path: '/used-product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellerSellerIdRoute = SellerSellerIdRouteImport.update({
  id: '/seller/$sellerId',
  path: '/seller/$sellerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceProductIdRoute = MarketplaceProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => MarketplaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/used-product/$productId': typeof UsedProductProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/used-product/$productId': typeof UsedProductProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/categories': typeof CategoriesRoute
  '/checkout': typeof CheckoutRoute
  '/marketplace': typeof MarketplaceRouteWithChildren
  '/orders': typeof OrdersRoute
  '/products': typeof ProductsRoute
  '/profile': typeof ProfileRoute
  '/marketplace/$productId': typeof MarketplaceProductIdRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/seller/$sellerId': typeof SellerSellerIdRoute
  '/used-product/$productId': typeof UsedProductProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/marketplace'
    | '/orders'
    | '/products'
    | '/profile'
    | '/marketplace/$productId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/used-product/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/marketplace'
    | '/orders'
    | '/products'
    | '/profile'
    | '/marketplace/$productId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/used-product/$productId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/cart'
    | '/categories'
    | '/checkout'
    | '/marketplace'
    | '/orders'
    | '/products'
    | '/profile'
    | '/marketplace/$productId'
    | '/product/$productId'
    | '/seller/$sellerId'
    | '/used-product/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CategoriesRoute: typeof CategoriesRoute
  CheckoutRoute: typeof CheckoutRoute
  MarketplaceRoute: typeof MarketplaceRouteWithChildren
  OrdersRoute: typeof OrdersRoute
  ProductsRoute: typeof ProductsRoute
  ProfileRoute: typeof ProfileRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
  SellerSellerIdRoute: typeof SellerSellerIdRoute
  UsedProductProductIdRoute: typeof UsedProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories': {
      id: '/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof CategoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/used-product/$productId': {
      id: '/used-product/$productId'
      path: '/used-product/$productId'
      fullPath: '/used-product/$productId'
      preLoaderRoute: typeof UsedProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seller/$sellerId': {
      id: '/seller/$sellerId'
      path: '/seller/$sellerId'
      fullPath: '/seller/$sellerId'
      preLoaderRoute: typeof SellerSellerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/$productId': {
      id: '/marketplace/$productId'
      path: '/$productId'
      fullPath: '/marketplace/$productId'
      preLoaderRoute: typeof MarketplaceProductIdRouteImport
      parentRoute: typeof MarketplaceRoute
    }
  }
}

interface MarketplaceRouteChildren {
  MarketplaceProductIdRoute: typeof MarketplaceProductIdRoute
}

const MarketplaceRouteChildren: MarketplaceRouteChildren = {
  MarketplaceProductIdRoute: MarketplaceProductIdRoute,
}

const MarketplaceRouteWithChildren = MarketplaceRoute._addFileChildren(
  MarketplaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CategoriesRoute: CategoriesRoute,
  CheckoutRoute: CheckoutRoute,
  MarketplaceRoute: MarketplaceRouteWithChildren,
  OrdersRoute: OrdersRoute,
  ProductsRoute: ProductsRoute,
  ProfileRoute: ProfileRoute,
  ProductProductIdRoute: ProductProductIdRoute,
  SellerSellerIdRoute: SellerSellerIdRoute,
  UsedProductProductIdRoute: UsedProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
